import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./carrito/carrito-context";
import Provider from "./components/session-provider";
import Footer from "./components/Footer";
import Header from "./components/header";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="antialiased pt-14">
        <Provider>
          <Header></Header>
          <CartProvider>{children}</CartProvider>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}